version: '3.9'

services:
  master:
    image: postgres:15
    environment:
      POSTGRES_USER: cluster
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: test_cluster
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - pgdata_master:/var/lib/postgresql/data
    networks:
      - pg_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 30s
      timeout: 10s
      retries: 5

  replica:
    image: postgres:15
    environment:
      POSTGRES_USER: cluster
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: test_cluster
      POSTGRES_REPLICATION_ROLE: "replica"
      POSTGRES_REPLICATION_USER: "replicator"
      POSTGRES_REPLICATION_PASSWORD: "replicatorpassword"
    volumes:
      - pgdata_replica:/var/lib/postgresql/data
    networks:
      - pg_network
    depends_on:
      - master
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata_master:
  pgdata_replica:

networks:
  pg_network:
